spring.application.name=emdr-connect

spring.datasource.url=jdbc:mysql://localhost:3306/emdr_connect
spring.datasource.username=root
spring.datasource.password=mnbvcxz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080